#! /bin/sh

#
# ~/.config/bspwm/bspwmrc
#

# behaviour
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

# workspaces
bspc monitor -d 1 2 3 4 5 6 7 8

# rules
bspc rule -a feh state=floating
bspc rule -a glfw state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled

# appearance
bspc config border_width    4
bspc config window_gap      8

# colors
bspc config normal_border_color     "#303030"
bspc config focused_border_color    "#b0b0b0"
bspc config presel_feedback_color   "#b0b0b0"

# autostart
if ! pgrep "sxhkd" > /dev/null; then
    sxhkd &
fi

if ! pgrep "unclutter" > /dev/null; then
    unclutter -root &
fi

if ! pgrep "udiskie" > /dev/null; then
    udiskie -2 &
fi

if ! pgrep "dunst" > /dev/null; then
    dunst &
else
    pkill dunst && dunst &
fi

if ! pgrep "compton" > /dev/null; then
    compton &
fi

xset s 300 5
if ! pgrep "xx-lock" > /dev/null; then
    xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock &
fi

~/.config/polybar/launch.sh &

xsetroot -cursor_name left_ptr &
setxkbmap -option caps:super
feh --bg-scale --no-fehbg ~/.config/wallpaper
